
title: Your awesome title
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - pagemaster

collections:
  test1:
    id_key: pid
    layout: default
    source: test1.csv
  test2:
    id_key: pid
    layout: default
    source: test2.json
  test3:
    id_key: pid
    layout: default
    source: test3.yml
